version: '3'

services:
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes: 
        - ./redis-service/config/redis.conf:/redis.conf
        # - ./redis-data:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
